app:
    resource: "@AppBundle/Controller/"
    type:     annotation

lightify_api:
    resource: "@RoleLightifyBundle/Resources/config/api.yml"
    prefix:   /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc